# ------------------------
## disable the logging in outputs folder.
# hydra:
#   output_subdir: null
#   run:
#     dir: .
rllib:
  enable_tuner: false
  storage_path: "~/DEV/ray_results"
  framework: "torch"
  use_new_API_stack: False      # using old stack for now
  num_gpus: 1
  num_cpus_for_main_process: 1  # This is only relevant when running RLlib through Tune. 
                                # Otherwise, `Algorithm.training_step()` runs in the main program (driver).
  num_env_runners: 10
  num_cpus_per_env_runner: 1
  num_envs_per_env_runner: 2   # >1 needed for ASYNC vectorization to be effective

agent:
  version: "PPO"                # "PPO" or "SAC"  
  # training
  gamma: 0.99
  lr: 1e-4
  train_batch_size : 4096        # `train_batch_size_per_learner` is its equivalent to new API stack
                                # The number of complete passes over the entire train batch
  minibatch_size: 64            # The size of minibatches to use to further split the train batch into
  shuffle_batch_per_epoch: True
  num_epochs: 10
  # evaluation
  evaluation_num_env_runners: 0
  evaluation_interval: 1        # Evaluate with every evaluation_interval training iterations. 
                                # The evaluation stats are reported under the “evaluation” metric key. 
                                # Set to None (or 0) for no evaluation.
  evaluation_duration: "auto"
  evaluation_duration_unit: "episode"

  # https://docs.ray.io/en/latest/rllib/rllib-algorithms.html#ppo
  PPO:
    use_critic: True
    use_gae: True
    lambda_: 0.95
    use_kl_loss: True
    kl_coeff: 0.2
    kl_target: 0.01
    entropy_coeff: 0.01    # prevent entropy runaway
    clip_param: 0.2        # tighter clipping for stability

  # https://docs.ray.io/en/latest/rllib/rllib-algorithms.html#sac
  SAC:
    target_network_update_freq: 32
env:
  # -----------------------------------------------
  # 2 RL agent variants:
  # refspeed (v0) or dynamicweights (v1). 
  env_version: "v0"
  # -----------------------------------------------
  # 4 collision avoidance (CA) variants:
  # noCA, manual, cost or constraint.
  subenv_version: "noCA"
  # -----------------------------------------------
  # ReferenceSpeedAction
  # For now, we use constant speed for the reference speed.
  # In future, other version may support variable speed.
  v0:
    action_dim: 1
  # -----------------------------------------------
  # DynamicWeightsAction
  v1:
    action_dim: 6
mpc:
  # -----------------------------------------------
  # action: acceleration, and steering.
  action_dim: 2
  # -----------------------------------------------
  # 4 collision avoidance (CA) variants:
  # noCA, manual, cost or constraint.
  CA_mode: "manual"       
  # -----------------------------------------------
  # Collision avoidance parameters:
  ttc_threshold: 3        # unit: second 
  detection_distance: 100 # unit: meter
  speed_override: 0
  # -----------------------------------------------
  # Configuration of highway-env env.
